create table if not exists products (
  id integer generated by default as identity primary key,
  name_zh text not null,
  name_en text not null,
  category text not null,
  storage_type text not null,
  supplier text,
  case_pack double precision,
  min_order_qty double precision,
  is_active boolean default true,
  sort_order integer
);

create table if not exists variants (
  id integer generated by default as identity primary key,
  product_id integer references products(id),
  form text not null,
  container text not null,
  conversion_to_base double precision,
  display_name_zh text not null,
  sort_order integer
);

create table if not exists inventory_balances (
  variant_id integer primary key references variants(id),
  on_hand double precision default 0
);

create table if not exists daily_counts (
  id integer generated by default as identity primary key,
  date text not null,
  variant_id integer references variants(id),
  counted_qty double precision not null,
  prev_on_hand double precision,
  adjustment double precision,
  created_at timestamp default now()
);

create table if not exists orders (
  id integer generated by default as identity primary key,
  order_date text not null,
  order_type text not null,
  status text default 'DRAFT',
  created_at timestamp default now()
);

create table if not exists order_lines (
  id integer generated by default as identity primary key,
  order_id integer references orders(id),
  product_id integer references products(id),
  suggested_qty double precision default 0,
  final_qty double precision default 0,
  unit text not null,
  reason_json jsonb,
  notes text
);

create table if not exists settings (
  key text primary key,
  value text not null
);

create table if not exists audit_logs (
  id bigserial primary key,
  table_name text not null,
  action text not null,
  row_id text,
  old_data jsonb,
  new_data jsonb,
  user_id uuid,
  created_at timestamp default now()
);
